[package]
name = "transaction-flood"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"

[dependencies]
deep_space = "0.1"
docopt = "1.1"
serde = "1.0"
reqwest = "0.9"
serde_json = "1.0"